1:  Mar 30 15:16:01 vpn gunicorn[26511]:   File "/opt/radiologger/venv/lib/python3.1
 2/site-packages/gunicorn/arbiter.py", line 228, in run                          
 Mar 30 15:16:01 vpn gunicorn[26511]:     self.halt(reason=inst.reason, exit_stat
 us=inst.exit_status)                                                            
 Mar 30 15:16:01 vpn gunicorn[26511]:   File "/opt/radiologger/venv/lib/python3.1
 2/site-packages/gunicorn/arbiter.py", line 341, in halt                         
 Mar 30 15:16:01 vpn gunicorn[26511]:     self.stop()                            
 Mar 30 15:16:01 vpn gunicorn[26511]:   File "/opt/radiologger/venv/lib/python3.1
 2/site-packages/gunicorn/arbiter.py", line 395, in stop                         
 Mar 30 15:16:01 vpn gunicorn[26511]:     time.sleep(0.1)                        
 Mar 30 15:16:01 vpn gunicorn[26511]:   File "/opt/radiologger/venv/lib/python3.1
 2/site-packages/gunicorn/arbiter.py", line 241, in handle_chld                  
 Mar 30 15:16:01 vpn gunicorn[26511]:     self.reap_workers()                    
 Mar 30 15:16:01 vpn gunicorn[26511]:   File "/opt/radiologger/venv/lib/python3.1
 2/site-packages/gunicorn/arbiter.py", line 529, in reap_workers                 
 Mar 30 15:16:01 vpn gunicorn[26511]:     raise HaltServer(reason, self.WORKER_BO
 OT_ERROR)                                                                       
 Mar 30 15:16:01 vpn gunicorn[26511]: gunicorn.errors.HaltServer: <HaltServer 'Wo
 rker failed to boot.' 3>                                                        
 Mar 30 15:16:01 vpn systemd[1]: radiologger.service: Main process exited, code=e
 xited, status=1/FAILURE                                                         
 Mar 30 15:16:01 vpn systemd[1]: radiologger.service: Failed with result 'exit-co
 de'.                                                                            
 
2:  root@vpn:~# sudo ls -la /opt/radiologger/.env                                   
 -rw------- 1 radiologger radiologger 732 Mar 30 15:02 /opt/radiologger/.env     
 
3: wort in mijn putty half weergegeven maar ik denk dat alles goed is daar:
 lxml_html_clean==0.4.1                                                          
 Mako==1.3.9                                                                     
 MarkupSafe==3.0.2                                                               
 packaging==24.2                                                                 
 psutil==7.0.0                                                                   
 psycopg2-binary==2.9.10                                                         
 python-dateutil==2.9.0.post0                                                    
 python-dotenv==1.1.0                                                            
 pytz==2025.2                                                                    
 regex==2024.11.6                                                                
 requests==2.32.3                                                                
 s3transfer==0.11.4                                                              
 setuptools==78.1.0                                                              
 six==1.17.0                                                                     
 SQLAlchemy==2.0.40                                                              
 tld==0.13                                                                       
 trafilatura==2.0.0                                                              
 typing_extensions==4.13.0                                                       
 tzlocal==5.3.1                                                                  
 urllib3==2.3.0                                                                  
 Werkzeug==3.1.3                                                                 
 wheel==0.45.1                                                                   
 WTForms==3.2.1                                                                  
 
4  radiologger --bind 0.0.0.0:5000                                                 
                                                                                 
 Error: [Errno 13] Permission denied: '/root'                                    
 
ik ben zelf als root ingelogd ik zou toch alles moeten mogen!

de njinx configuratie lijkt in orde
 root@vpn:~# sudo nginx -t                                                       
 nginx: the configuration file /etc/nginx/nginx.conf syntax is ok                
 nginx: configuration file /etc/nginx/nginx.conf test is successful              
 